### PR TITLE
Updated Support Ticket Hyperlink in README.md

### PR DESCRIPTION
**Pull request by shsnip**
Replaced Support Ticket Location 'email.html' to 'email.md'

### CODE REVIEW

**Comment by gxres042** [comment]
`.html` is right.
You may get an HTTP 404 when use `.md`
Or....I'm outdated?

**Review by gxres042 — APPROVED** [review]

**Comment by coresnip** [comment]
Sorry my bad. I am a dumb person. Using '.md' works fine in the repository but will break the website

**Comment by tnqzh123** [comment]
Actually, `.md` will be converted to `.html` when the website build, and it's recommended by VuePress.

https://v1.vuepress.vuejs.org/guide/markdown.html

**Comment by coresnip** [comment]
> Actually, `.md` will be converted to `.html` when the website build, and it's recommended by VuePress.
> 
> https://v1.vuepress.vuejs.org/guide/markdown.html

i do not know if this is the right place to ask, but how to i start translating  the manual to English or Hindi.

**Comment by gxres042** [comment]
> i do not know if this is the right place to ask, but how to i start translating the manual to English or Hindi.

Actually we started a English-translated project for manual.

https://github.com/LittleSkinCommspt/LittleSkinManualDev

**Comment by coresnip** [comment]
> Actually we started a English-translated project for manual.
> 
> https://github.com/LittleSkinCommspt/LittleSkinManualDev

Well I think that the translation is already done for files listed in 'en' directory.

**Pull request closed without merging**
